<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IconsistenceController extends Controller
{
    public function local_giro(){
        //...
        //...   
        //...
        //...
    }
    public function proveedor_proveedor(){
        //...
        //...   
        //...
        //...
    }
}
